FROM node:8.9-alpine

USER root

# install git
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

# install Chrome
RUN wget -q -O chrome64_63.0.3239.108.deb https://www.slimjet.com/chrome/download-chrome.php?file=lnx%2Fchrome64_63.0.3239.108.deb
RUN dpkg -i chrome64_63.0.3239.108.deb; apt-get -fy install

RUN mkdir /app
WORKDIR /app
COPY /test/ /app/

RUN npm i
