FROM node:8.9.4

USER root

RUN apt-get update
RUN apt-get install git

# install Chromebrowser
RUN \
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
  echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list && \
  apt-get update && \
  apt-get install -y dbus-x11 google-chrome-stable && \
  rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app

COPY /test/ /app/
COPY /stryker.conf.js /app/stryker.conf.js
RUN npm i

## Install stryker
RUN npm i --save-dev stryker@0.29.2 stryker-api@0.21.1 stryker-html-reporter@0.16.2 stryker-jasmine@0.10.2 stryker-javascript-mutator@0.10.0 stryker-karma-runner@0.18.1
