FROM node:8.9-alpine

USER root

# install git
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

RUN apk update && apk upgrade \
  && echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories \
  && echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories \
  && apk add --no-cache \
  chromium@edge \
  nss@edge \
  && rm -rf /var/lib/apt/lists/* \
  /var/cache/apk/* \
  /usr/share/man \
  /tmp/*

ENV CHROME_BIN=/usr/bin/chromium-browser \
CHROME_PATH=/usr/lib/chromium/

RUN mkdir /app
WORKDIR /app
COPY /test/ /app/

RUN npm i
