FROM alpine:3.7

RUN apk --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ add android-tools

RUN mkdir /app
RUN mkdir /app/reports
WORKDIR /app

COPY app.apk /app/app.apk

COPY entry.sh /usr/app/entry.sh
RUN chmod +x /usr/app/entry.sh

ENTRYPOINT ["/usr/app/entry.sh"]
