FROM node:8.9-alpine

USER root

RUN mkdir /app
RUN mkdir /app/reports
WORKDIR /app

# Install Java.
RUN apk update
RUN apk fetch openjdk8
RUN apk add openjdk8

COPY package.json /app/package.json
COPY wdio.conf.js /app/wdio.conf.js
COPY /test/ /app/test/

RUN apk --no-cache add --virtual native-deps \
  g++ gcc libgcc libstdc++ linux-headers make python && \
  npm install --quiet node-gyp -g &&\
  npm install --quiet && \
  apk del native-deps g++ gcc linux-headers make python
