FROM java:8-jdk

USER root

# Install dependencies
RUN apt-get update
RUN apt-get -y install lib32stdc++6 lib32z1 lib32z1-dev
RUN apt-get install git

RUN mkdir /app
RUN mkdir /app/reports
WORKDIR /app

RUN git clone https://github.com/ravelinx22/LimitedMutAPK.git

COPY app.apk /app/LimitedMutAPK/app.apk

WORKDIR /app/LimitedMutAPK

RUN mkdir mutants

COPY entry.sh /app/LimitedMutAPK/entry.sh
RUN chmod +x /app/LimitedMutAPK/entry.sh

ENTRYPOINT ["/app/LimitedMutAPK/entry.sh"]
