FROM node:8.9.4

USER root

RUN apt-get -y install python-software-properties

# Install android dependencies
RUN apt-get update
RUN apt-get -y install lib32stdc++6 lib32z1 lib32z1-dev
RUN apt-get install git

# Install Java.
RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer

# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle

RUN mkdir /app
RUN mkdir /app/reports
WORKDIR /app

RUN git clone https://github.com/ravelinx22/LimitedMutAPK.git

COPY app.apk /app/LimitedMutAPK/app.apk

WORKDIR /app/LimitedMutAPK

RUN mkdir mutants
