FROM node:8.9.4

USER root

RUN apt-get -y install python-software-properties

# Install android dependencies
RUN apt-get update
RUN apt-get -y install lib32stdc++6 lib32z1 lib32z1-dev
RUN apt-get install git
ENV ANDROID_HOME /usr/local/android-sdk
ENV GRADLE_HOME /usr/local/gradle
ENV ANDROID_SDK_HOME $ANDROID_HOME
ENV PATH $PATH:$ANDROID_SDK_HOME/tools
ENV PATH $PATH:$ANDROID_SDK_HOME/platform-tools
ENV JAVA_HOME /usr/lib/jvm/java-7-oracle

RUN mkdir /app
RUN mkdir /app/reports
WORKDIR /app

RUN git clone https://github.com/ravelinx22/LimitedMutAPK.git

COPY app.apk /app/LimitedMutAPK/app.apk

WORKDIR /app/LimitedMutAPK

RUN mkdir mutants
